name 'httpd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures httpd'
long_description 'Installs/Configures httpd'
version '0.1.0'

issues_url 'https://github.com/arubiero/httpd.git'
source_url 'https://github.com/arubiero/httpd.git'
